ktor:
  application:
    modules:
      - org.drewcarlson.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
